services:
  oracledb:
    image: container-registry.oracle.com/database/enterprise:19.19.0.0
    container_name: ora_db_19c_ent_01
    restart: unless-stopped
    ports:
      - ${ORACLE_PDB_LOCAL_PORT}:1521       # Listener / TNS
      - ${ORACLE_PDB_LOCAL_OEM_PORT}:5500   # EM Express (HTTPS)
    environment:
      ORACLE_SID: ${ORACLE_SID}
      ORACLE_PDB: ${ORACLE_PDB}
      ORACLE_PWD: ${ORACLE_PDB_SID_PWD}
      ORACLE_CHARACTERSET: AL32UTF8
      ENABLE_ARCHIVELOG: true
    volumes:
      - ./oradata:/opt/oracle/oradata:U
      - ./scripts/setup:/opt/oracle/scripts/setup
      - ./scripts/startup:/opt/oracle/scripts/startup
