-- Create 'ORACLE_SAMPLE_PDB' PDB using the default 'ORCLPDB1' PDB that 
-- the container creates as a template.
-- 
-- sql ORACLE_SAMPLE/someThing#64@localhost:1521/ORACLE_SAMPLE_PDB
--
CREATE PLUGGABLE DATABASE ORACLE_SAMPLE_PDB 
FROM ORCLPDB1 STORAGE UNLIMITED TEMPFILE REUSE FILE_NAME_CONVERT=('ORCLPDB1', 'ORACLE_SAMPLE_PDB')
DEFAULT TABLESPACE DATA;

ALTER PLUGGABLE DATABASE ORACLE_SAMPLE_PDB OPEN READ WRITE;

-- Change session to Pluggable DataBase (PDB).
ALTER SESSION SET container = ORACLE_SAMPLE_PDB;

-- Create 'ORACLE_SAMPLE' user/schema.
CREATE USER ORACLE_SAMPLE IDENTIFIED BY "Oracle_Sample#92" PROFILE
DEFAULT ACCOUNT UNLOCK;

-- Assign 'ORACLE_SAMPLE' user/schema to default to the DATA and TEMP tablespaces in the PDB.
ALTER USER ORACLE_SAMPLE DEFAULT TABLESPACE DATA QUOTA UNLIMITED ON DATA;

ALTER USER ORACLE_SAMPLE TEMPORARY TABLESPACE TEMP;

-- Grant priveleges to 'ORACLE_SAMPLE' user/schema.
GRANT CONNECT TO ORACLE_SAMPLE;
GRANT RESOURCE TO ORACLE_SAMPLE;
GRANT CREATE ANY VIEW TO ORACLE_SAMPLE;

GRANT ALL PRIVILEGES to ORACLE_SAMPLE;

GRANT SELECT ON SYS.DBA_RECYCLEBIN TO ORACLE_SAMPLE;